spring:
  datasource:
    username: root
    password: 123qwe
    url: jdbc:mysql://localhost:3306/elasticsearch_entire?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
